### ISSUE TITLE
Error rendering model

### ISSUE THREAD

**Issue by joaomlap** [Kitware/trame-vtklocal#16]
Hi,

Not sure if this is helpful at all but while following the steps here:
https://www.kitware.com/vtk-wasm-and-its-trame-integration/

I was able to render some parts of my big-ish model but when trying to render the full thing I got some errors:

Python Server:
```
 JS Error => 2024-10-29 16:11:06.364 (  78.142s) [          401734]vtkGenericDataArray.txx:378    ERR| vtkTypeInt64Array (0xffe85080): Unable to allocate 476064 elements of size 8 bytes.
 JS Error => WASM update failed
 JS Error => RuntimeError: null function or function signature mismatch
 ```

Browser console;
```
2024-10-29 16:27:10.215 (  76.527s) [          401734]vtkGenericDataArray.txx:378    ERR| vtkTypeInt64Array (0xffe850e8): Unable to allocate 476064 elements of size 8 bytes. 
overrideMethod @ hook.js:608
Show 1 more frame
Show less

hook.js:608 WASM update failed
overrideMethod @ hook.js:608
Show 1 more frame
Show less

trame_vtklocal.umd.js:1 4293415576
hook.js:608 RuntimeError: null function or function signature mismatch
    at vtkWasmSceneManager.wasm:0xa84d04
    at vtkWasmSceneManager.wasm:0xfbdd5a
    at dynCall (vtkWasmSceneManager.mjs:9:73159)
    at vtkWasmSceneManager.mjs:9:73240
    at Object.startEventLoop (eval at newFunc (vtkWasmSceneManager.mjs:9:68337), <anonymous>:8:10)
    at trame_vtklocal.umd.js:1:7497
```

**Comment by jourdain** [comment]
Can you describe the geometry in question? Multi-block, number of blocks, number of cells, number of points...
Just so we have some idea of what you are talking about in term of big-ish model?

**Comment by jspanchu** [comment]
@joaomlap I think your mesh is really big. The error basically says that VTK failed to allocate almost 3.6 GB. Since the memory limit in wasm32 is 4GB it is quite easy for applications to run out of memory. I guess the extra 400 megabytes are used for small allocations internal to VTK used to store the state/blobs in C++ object manager memory.

@jourdain We need a way for trame to optionally use wasm64.

**Comment by jourdain** [comment]
Yes we will enable such option once wasm64 is more widely supported
