### ISSUE TITLE
VTK serialization

### ISSUE THREAD

**Issue by jourdain** [Kitware/trame-vtklocal#3]
- ./examples/vtk/charts_scatter.py
  - [ ] vtkContextInteractorStyle
  - [ ] vtkOpenGLContextActor
 - ./examples/vtk/silhouette.py
   - local interactor not picking up camera update
 - ./examples/vtk/widgets_*.py
   - no widget interaction
   - Some rep missing

**Comment by jourdain** [comment]
@jspanchu I've added I think most of the examples we care about. Ideally we can make most of them works with WASM.

**Comment by jspanchu** [comment]
> - ./examples/vtk/silhouette.py
>    local interactor not picking up camera update

So, there is another issue with silhouette where if you dragged the slider and changed the resolution of the cone, the silhouette on the client was not correct. this is fixed by https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11113

Other than that, it also needs to synchronize the local camera with server side camera. this was discussed in #4

**Comment by jspanchu** [comment]
I'm unable to get any of the pyvista examples running when I use developer VTK (not from pip install). Any pointers?

```
python examples/pyvista/basic.py --server
Traceback (most recent call last):
  File "examples/pyvista/basic.py", line 57, in <module>
    app = TrameApp()
  File "examples/pyvista/basic.py", line 34, in __init__
    self.render_window = setup_pyvista()
  File "examples/pyvista/basic.py", line 17, in setup_pyvista
    mesh = examples.download_st_helens()
  File "/home/local/KHQ/jaswant.panchumarti/dev/trame-vtklocal/.venv/lib/python3.8/site-packages/pyvista/examples/downloads.py", line 425, in download_st_helens
    return _download_and_read('SainteHelens.dem', load=load)
  File "/home/local/KHQ/jaswant.panchumarti/dev/trame-vtklocal/.venv/lib/python3.8/site-packages/pyvista/examples/downloads.py", line 260, in _download_and_read
    return read(saved_file, file_format=file_format)
  File "/home/local/KHQ/jaswant.panchumarti/dev/trame-vtklocal/.venv/lib/python3.8/site-packages/pyvista/core/utilities/fileio.py", line 201, in read
    mesh = reader.read()
  File "/home/local/KHQ/jaswant.panchumarti/dev/trame-vtklocal/.venv/lib/python3.8/site-packages/pyvista/core/utilities/reader.py", line 387, in read
    data._restore_metadata()
  File "/home/local/KHQ/jaswant.panchumarti/dev/trame-vtklocal/.venv/lib/python3.8/site-packages/pyvista/core/dataobject.py", line 192, in _restore_metadata
    if key in fdata:
TypeError: argument of type 'vtkmodules.vtkCommonDataModel.vtkFieldData' is not iterable
```

**Comment by jspanchu** [comment]
Sorted it out by using https://github.com/pyvista/pyvista/pull/5650

**Comment by jspanchu** [comment]
I've updated the description to reflect what's currently working and what isn't

**Comment by jourdain** [comment]
- [ ] vtkSliderRepresentation2D
- [ ] vtk charts
